name: Tweet Bot # ワークフロー名
# 発火タイミング  日本時刻の朝7時に定期処理(分 時 日 月 曜日(0が日曜))  UTC の 02:00 は JST だと 11:00 。
#(UTC)日本時刻から9時間マイナスで設定する
on:
  push:
#   schedule:
#     - cron: '50 12 * * *'
env:
  TWITTER_API_CONSUMER_KEY : ${{secrets.TWITTER_API_CONSUMER_KEY}}
  TWITTER_API_CONSUMER_SECRET : ${{secrets.TWITTER_API_CONSUMER_SECRET}}
  TWITTER_API_ACCESS_TOKEN_KEY : ${{secrets.TWITTER_API_ACCESS_TOKEN_KEY}}
  TWITTER_API_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_API_ACCESS_TOKEN_SECRET}}
jobs:
  build:
    runs-on: ubuntu-latest # Ubuntuの最新版環境内で処理を実行することを指定
    # 実行する処理＆コマンド指定
    steps:
      # リポジトリからチェックアウトして以下の処理を実行していく
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install tweepy
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
